- repo: local
  hooks:
    - id: rust-clippy
      name: Rust clippy
      description: Run cargo clippy on files included in the commit.
      entry: cargo clippy --all-targets --all-features -- -D warnings
      pass_filenames: false
      types: [file, rust]
      language: system
    - id: rust-linting
      name: Rust linting
      description: Run cargo fmt on files included in the commit.
      entry: cargo fmt --all --
      pass_filenames: true
      types: [file, rust]
      language: system
    - id: rust-tests
      name: Rust tests
      description: Run cargo test.
      entry: cargo test
      pass_filenames: false
      types: [file, rust]
      language: system
